### PR TITLE
feat: implement map query for bibliography #109

### PR DESCRIPTION
**Pull request by ttechnicus**
Implemented map query for bibliography launched from the bibl. query form

### CODE REVIEW

**Review by ctot-nondef — COMMENTED** [review]
looks good and basically works, one question though: where does the title prop go? It doesn't seem to be applied to the window

**Comment by ttechnicus** [comment]
@ctot-nondef The user story is:

1. Open a bibliography query window (e. g. click menu: Bibliographies > Explanation; then click a "→Text" link in the text which will open a query window with the corresponding query)
2. Expand the form (if it is closed) by clicking on the query expression on the top
3. (Optional) change the query string
4. Tick in "Display on map"
5. Click the Query button.

Expected result: a new map window should open with the query results, and the title of **this** window is `Bibl. Locations for "${queryString.value}"`.

**Review by simar0at — APPROVED** [review]
The layer selector could be the window title but it is bibl_markers_tei:hello: for the layer. We can change that later.

**Comment by ttechnicus** [comment]
@simar0at The layer selector text is an unrelated issue. I created a task for it in #114

**Pull request merged**
